import os
import subprocess
import asyncio
import chromadb
from ollama import AsyncClient
import chainlit as cl
from pypdf import PdfReader
from fpdf import FPDF
from datetime import datetime

# 1. Force local-only communication for OPSEC
os.environ["OLLAMA_HOST"] = "127.0.0.1"

# 2. Setup Clients and Configuration
# Initialize Local Vector DB for Long-term memory
chroma_client = chromadb.PersistentClient(path="./mission_db")
collection = chroma_client.get_or_create_collection(name="mission_archive")

client = AsyncClient(host="http://127.0.0.1:11434")

# TEXT_MODEL: Deep reasoning and RAG
# If 26b is still slow, try "gemma4:9b" to verify the pipeline first
TEXT_MODEL = "gemma4:26b" 
# VISION_MODEL: Optimized for tactical image analysis
VISION_MODEL = "moondream" 

def secure_shred(file_path):
    """3-pass overwrite of the file before deletion (macOS native)."""
    try:
        subprocess.run(["rm", "-P", file_path], check=True)
        return True
    except: return False

def create_sitrep_pdf(content, filename="SITREP.pdf"):
    """Generates a structured military-style PDF from analyzed content."""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Courier", "B", 16)
    pdf.cell(0, 10, "TACTICAL INTELLIGENCE NODE - SITREP", ln=True, align='C')
    pdf.set_font("Courier", "", 10)
    pdf.cell(0, 5, f"TIMESTAMP: {datetime.now().strftime('%d%H%M%b%y').upper()}", ln=True, align='C')
    pdf.cell(0, 5, "CLASSIFICATION: FOR OFFICIAL USE ONLY // LOCAL-ONLY", ln=True, align='C')
    pdf.ln(10)
    
    # Body
    pdf.set_font("Courier", "", 11)
    # Handle encoding for special characters
    clean_text = content.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 5, clean_text)
    
    # Footer
    pdf.set_y(-20)
    pdf.set_font("Courier", "I", 8)
    pdf.cell(0, 10, "Generated by Defense Node (Local-Inference). Purge after use.", align='C')
    
    pdf.output(filename)
    return filename

@cl.on_chat_start
async def start():
    # Welcome message reflecting all active capabilities
    await cl.Message(content="🛡️ **Defense Node Active.** (RAG + Vision + Reporting Enabled). Upload files or query the archive.").send()

@cl.action_callback("gen_sitrep")
async def on_action(action: cl.Action):
    """Triggered when the user clicks 'Generate Formal SITREP'"""
    # Retrieve the last analysis from the user session
    report_text = cl.user_session.get("last_analysis")
    if not report_text:
        await cl.Message(content="❌ No analysis data found to export.").send()
        return

    pdf_path = create_sitrep_pdf(report_text)
    
    # Send the generated PDF as an element
    elements = [cl.File(name="SITREP_Output.pdf", path=pdf_path, display="inline")]
    await cl.Message(content="✅ **Formal SITREP Generated.**", elements=elements).send()
    
    # Security: Wait 60s for download, then shred
    await asyncio.sleep(60)
    secure_shred(pdf_path)

@cl.on_message
async def main(message: cl.Message):
    # --- PHASE 1: DOCUMENT & IMAGE INGESTION ---
    if message.elements:
        for element in message.elements:
            # --- HANDLE PDF (RAG + SUMMARIZATION) ---
            if element.type == "file" and element.name.endswith(".pdf"):
                status_msg = cl.Message(content=f"📑 **Indexing PDF:** `{element.name}`...")
                await status_msg.send()

                reader = PdfReader(element.path)
                full_text = ""
                # Chunking strategy: Index page by page into the Vector DB with metadata
                for i, page in enumerate(reader.pages):
                    page_text = page.extract_text()
                    if page_text.strip():
                        full_text += page_text
                        collection.add(
                            documents=[page_text],
                            metadatas=[{"source": element.name, "page": i+1}],
                            ids=[f"{element.name}_pg_{i}"]
                        )
                
                if len(full_text) < 50:
                    status_msg.content = "⚠️ Extraction failed or text too short."
                    await status_msg.update()
                    return

                status_msg.content = f"🧠 **Analyzing {len(full_text)} characters...**"
                await status_msg.update()

                ui_msg = cl.Message(content=f"### Summary: {element.name}\n\n")
                await ui_msg.send()

                full_response = ""
                try:
                    async for part in await client.chat(
                        model=TEXT_MODEL,
                        messages=[
                            {"role": "system", "content": """
                            You are a Senior Intelligence Analyst. Summarize this document using BLUF format. 
                            Identify KEY FINDINGS, IDENTIFIED RISKS, and DISCREPANCIES.
                            Be precise with coordinates and timestamps.
                            """},
                            {"role": "user", "content": f"Document Content: {full_text}"}
                        ],
                        stream=True,
                    ):
                        token = part['message']['content']
                        full_response += token
                        await ui_msg.stream_token(token)
                    
                    # Save context for PDF export
                    cl.user_session.set("last_analysis", full_response)
                    actions = [cl.Action(name="gen_sitrep", label="📄 Generate Formal SITREP", value="pdf", description="Export to PDF", payload={})]
                    await cl.Message(content="---", actions=actions).send()

                except Exception as e:
                    await cl.Message(content=f"❌ **Inference Error:** {str(e)}").send()

                await ui_msg.update()
                secure_shred(element.path)
                await cl.Message(content=f"🔒 `{element.name}` purged from disk.").send()

            # --- HANDLE IMAGES (VISUAL INTEL) ---
            elif element.type == "image":
                status_msg = cl.Message(content=f"📸 **Analyzing Visual Intel:** `{element.name}`...")
                await status_msg.send()

                ui_msg = cl.Message(content=f"### Visual Analysis: {element.name}\n\n")
                await ui_msg.send()

                full_response = ""
                try:
                    async for part in await client.chat(
                        model=VISION_MODEL,
                        messages=[{
                            "role": "user", 
                            "content": "Identify tactical landmarks, vehicles, and threats. Clinical tone.",
                            "images": [element.path]
                        }],
                        stream=True,
                    ):
                        token = part['message']['content']
                        full_response += token
                        await ui_msg.stream_token(token)
                    
                    # Store response for PDF export and show button
                    cl.user_session.set("last_analysis", full_response)
                    actions = [cl.Action(name="gen_sitrep", label="📄 Generate Formal SITREP", value="pdf", description="Export to PDF", payload={})]
                    await cl.Message(content="---", actions=actions).send()

                except Exception as e:
                    await cl.Message(content=f"❌ **Vision Error:** {str(e)}").send()

                await ui_msg.update()
                await status_msg.remove()
                secure_shred(element.path)
                await cl.Message(content=f"🔒 Visual data `{element.name}` purged.").send()
        return

    # --- PHASE 2: LONG-TERM MEMORY RETRIEVAL (RAG) ---
    if not message.elements:
        search_status = cl.Message(content="🔍 **Searching Archive...**")
        await search_status.send()

        results = collection.query(query_texts=[message.content], n_results=3)
        context_blocks = []
        source_metadata = []
        
        if results['documents']:
            for doc, meta in zip(results['documents'][0], results['metadatas'][0]):
                citation = f"[{meta['source']}, Pg {meta['page']}]"
                context_blocks.append(f"SOURCE {citation}:\n{doc}")
                source_metadata.append(citation)

        retrieved_context = "\n\n".join(context_blocks) if context_blocks else "No archived data found."
        unique_sources = ", ".join(list(set(source_metadata)))

        ui_msg = cl.Message(content="")
        await ui_msg.send()

        full_response = ""
        try:
            async for part in await client.chat(
                model=TEXT_MODEL,
                messages=[
                    {"role": "system", "content": f"You are a Tactical Analyst. Cite sources [File, Pg X].\n\nCONTEXT:\n{retrieved_context}"},
                    {"role": "user", "content": message.content}
                ],
                stream=True,
            ):
                token = part['message']['content']
                full_response += token
                await ui_msg.stream_token(token)
            
            if source_metadata:
                footer = f"\n\n---\n**Verified Sources:** {unique_sources}"
                await ui_msg.stream_token(footer)
                full_response += footer
            
            # Store response for PDF export and show button
            cl.user_session.set("last_analysis", full_response)
            actions = [cl.Action(name="gen_sitrep", label="📄 Generate Formal SITREP", value="pdf", description="Export to PDF", payload={})]
            await cl.Message(content="---", actions=actions).send()

        except Exception as e:
            await cl.Message(content=f"❌ **Search Error:** {str(e)}").send()

        await search_status.remove() 
        await ui_msg.update()